# Generated by Django 4.2.16 on 2026-05-25 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(choices=[('FUEL_STATIONARY', 'Stationary Combustion'), ('FUEL_MOBILE', 'Mobile Combustion'), ('ELECTRICITY', 'Purchased Electricity'), ('TRAVEL_AIR', 'Air Travel'), ('TRAVEL_HOTEL', 'Hotel Stay'), ('TRAVEL_GROUND', 'Ground Transport'), ('PROCUREMENT', 'Purchased Goods & Services')], max_length=30)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('facility_code', models.CharField(blank=True, max_length=100)),
                ('facility_name', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('activity_quantity_source', models.DecimalField(decimal_places=6, max_digits=20)),
                ('activity_unit_source', models.CharField(max_length=50)),
                ('activity_quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('activity_unit', models.CharField(max_length=50)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=10, help_text='kg CO2e per activity_unit', max_digits=20, null=True)),
                ('emission_factor_source', models.CharField(blank=True, help_text="e.g. 'DEFRA 2023 v1.1', 'EPA eGRID 2022'", max_length=255)),
                ('raw_data', models.JSONField(help_text='Exact original row from the source file. Never modified.')),
                ('source_row_ref', models.CharField(blank=True, help_text='Row number or document ID in the source file', max_length=255)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('flag_reasons', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked for Audit')], default='PENDING', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('is_manually_edited', models.BooleanField(default=False)),
                ('edit_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.ingestionjob')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['org', 'status'], name='emissions_e_org_id_1d3e0a_idx'), models.Index(fields=['org', 'scope'], name='emissions_e_org_id_f715c3_idx'), models.Index(fields=['org', 'category'], name='emissions_e_org_id_5d6d86_idx'), models.Index(fields=['job'], name='emissions_e_job_id_8a8937_idx')],
            },
        ),
    ]
