# Generated by Django 4.2.16 on 2026-05-25 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_FLAT_FILE', 'SAP Flat File (SE16/ALV CSV)'), ('UTILITY_CSV', 'Utility Portal CSV'), ('TRAVEL_CSV', 'Travel Platform CSV (Concur/Navan)')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('uploaded_file', models.FileField(upload_to='ingestion/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('row_count_total', models.IntegerField(default=0)),
                ('row_count_parsed', models.IntegerField(default=0)),
                ('row_count_failed', models.IntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('error_detail', models.TextField(blank=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ParseError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_ref', models.CharField(max_length=100)),
                ('raw_content', models.TextField()),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parse_errors', to='ingestion.ingestionjob')),
            ],
            options={
                'ordering': ['row_ref'],
            },
        ),
    ]
